import { Router } from 'express';
import validate from '../../middlewares/validate.middleware.js';
import { protect } from '../../middlewares/auth.middleware.js';
import { authorize } from '../../middlewares/role.middleware.js';
import { upload } from '../../middlewares/upload.middleware.js';
import { STAFF_ROLES } from '../../utils/constants.js';
import * as controller from './media.controller.js';
import { eventMediaSchema, idSchema, listMediaSchema } from './media.validator.js';
const router = Router();
router.use(protect, authorize(...STAFF_ROLES));
router.post('/events/:eventId/poster', validate(eventMediaSchema), upload.single('file'), controller.uploadEventPoster);
router.post('/events/:eventId/gallery', validate(eventMediaSchema), upload.fields([{ name: 'files', maxCount: 12 }, { name: 'file', maxCount: 12 }]), controller.uploadEventGallery);
router.post('/', upload.single('file'), controller.uploadMedia);
router.get('/', validate(listMediaSchema), controller.listMedia);
router.delete('/:id', validate(idSchema), controller.deleteMedia);
export default router;
