import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import mongoSanitize from 'express-mongo-sanitize';
import hpp from 'hpp';
import morgan from 'morgan';
import cookieParser from 'cookie-parser';
import path from 'path';
import { fileURLToPath } from 'url';
import { corsOptions } from './config/cors.js';
import { env } from './config/env.js';
import { apiLimiter } from './middlewares/rateLimit.middleware.js';
import { errorHandler, notFound } from './middlewares/error.middleware.js';

import authRoutes from './modules/auth/auth.routes.js';
import profileRoutes from './modules/profile/profile.routes.js';
import userRoutes from './modules/users/user.routes.js';
import eventRoutes from './modules/events/event.routes.js';
import hallRoutes from './modules/halls/hall.routes.js';
import showtimeRoutes from './modules/showtimes/showtime.routes.js';
import seatRoutes from './modules/seats/seat.routes.js';
import bookingRoutes from './modules/bookings/booking.routes.js';
import paymentRoutes from './modules/payments/payment.routes.js';
import ticketRoutes from './modules/tickets/ticket.routes.js';
import refundRoutes from './modules/refunds/refund.routes.js';
import notificationRoutes from './modules/notifications/notification.routes.js';
import reportRoutes from './modules/reports/report.routes.js';
import dashboardRoutes from './modules/dashboard/dashboard.routes.js';
import settingsRoutes from './modules/settings/settings.routes.js';
import auditLogRoutes from './modules/auditLogs/auditLog.routes.js';
import mediaRoutes from './modules/media/media.routes.js';
import boxOfficeRoutes from './modules/boxOffice/boxOffice.routes.js';
import { eventShowtimes } from './modules/showtimes/showtime.controller.js';
import validate from './middlewares/validate.middleware.js';
import { eventShowtimesSchema } from './modules/showtimes/showtime.validator.js';
import { publicVerify } from './modules/tickets/ticket.controller.js';
import { qrParamSchema } from './modules/tickets/ticket.validator.js';

const app = express();
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

if (env.TRUST_PROXY) app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors(corsOptions));
app.use(cookieParser());
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));
app.use(mongoSanitize());
app.use(hpp());
app.use(morgan(env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use(apiLimiter);
app.use(`/${env.UPLOAD_DIR}`, express.static(path.resolve(__dirname, '..', '..', env.UPLOAD_DIR)));

const healthHandler = (req, res) => res.json({ success: true, message: 'Tiatru backend is healthy', uptime: process.uptime(), timestamp: new Date().toISOString() });
app.get('/health', healthHandler);

const api = express.Router();
api.get('/health', healthHandler);
api.use('/auth', authRoutes);
api.use('/profile', profileRoutes);
api.use('/users', userRoutes);
api.get('/events/:eventId/showtimes', validate(eventShowtimesSchema), eventShowtimes);
api.use('/events', eventRoutes);
api.use('/halls', hallRoutes);
api.use('/showtimes', showtimeRoutes);
api.use('/', seatRoutes);
api.use('/bookings', bookingRoutes);
api.use('/box-office', boxOfficeRoutes);
api.use('/payments', paymentRoutes);
api.use('/tickets', ticketRoutes);
api.get('/verify-ticket/:qrToken', validate(qrParamSchema), publicVerify);
api.use('/refunds', refundRoutes);
api.use('/notifications', notificationRoutes);
api.use('/reports', reportRoutes);
api.use('/dashboard', dashboardRoutes);
api.use('/settings', settingsRoutes);
api.use('/audit-logs', auditLogRoutes);
api.use('/media', mediaRoutes);

app.use(env.API_PREFIX, api);
app.use(notFound);
app.use(errorHandler);

export default app;
