export const ROLES = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  BOX_OFFICE: 'BOX_OFFICE',
  EVENT_MANAGER: 'EVENT_MANAGER',
  FINANCE: 'FINANCE',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN'
});

export const STAFF_ROLES = [ROLES.BOX_OFFICE, ROLES.EVENT_MANAGER, ROLES.FINANCE, ROLES.ADMIN, ROLES.SUPER_ADMIN];
export const ADMIN_ROLES = [ROLES.ADMIN, ROLES.SUPER_ADMIN];
export const EVENT_MANAGER_ROLES = [ROLES.EVENT_MANAGER, ROLES.ADMIN, ROLES.SUPER_ADMIN];
export const FINANCE_ROLES = [ROLES.FINANCE, ROLES.ADMIN, ROLES.SUPER_ADMIN];
export const BOX_OFFICE_ROLES = [ROLES.BOX_OFFICE, ROLES.ADMIN, ROLES.SUPER_ADMIN];

export const USER_STATUS = Object.freeze({ ACTIVE: 'ACTIVE', BLOCKED: 'BLOCKED', DELETED: 'DELETED' });
export const EVENT_STATUS = Object.freeze({ DRAFT: 'DRAFT', PUBLISHED: 'PUBLISHED', ARCHIVED: 'ARCHIVED', CANCELLED: 'CANCELLED' });
export const HALL_STATUS = Object.freeze({ ACTIVE: 'ACTIVE', MAINTENANCE: 'MAINTENANCE', INACTIVE: 'INACTIVE' });
export const SHOWTIME_STATUS = Object.freeze({ SCHEDULED: 'SCHEDULED', ON_SALE: 'ON_SALE', SOLD_OUT: 'SOLD_OUT', CANCELLED: 'CANCELLED', COMPLETED: 'COMPLETED' });
export const SEAT_CATEGORY = Object.freeze({ VIP: 'VIP', STANDARD: 'STANDARD', STUDENT: 'STUDENT' });
export const SEAT_LOCK_STATUS = Object.freeze({ ACTIVE: 'ACTIVE', EXPIRED: 'EXPIRED', RELEASED: 'RELEASED', CONVERTED: 'CONVERTED' });
export const BOOKING_STATUS = Object.freeze({ PENDING: 'PENDING', RESERVED: 'RESERVED', PAID: 'PAID', CANCELLED: 'CANCELLED', EXPIRED: 'EXPIRED', REFUNDED: 'REFUNDED' });
export const BOOKING_SOURCE = Object.freeze({ ONLINE: 'ONLINE', BOX_OFFICE: 'BOX_OFFICE' });
export const TICKET_STATUS = Object.freeze({ VALID: 'VALID', USED: 'USED', CANCELLED: 'CANCELLED', REFUNDED: 'REFUNDED', EXPIRED: 'EXPIRED' });
export const PAYMENT_STATUS = Object.freeze({ PENDING: 'PENDING', SUCCESS: 'SUCCESS', FAILED: 'FAILED', REFUNDED: 'REFUNDED' });
export const PAYMENT_PROVIDER = Object.freeze({ IYZICO: 'IYZICO', STRIPE: 'STRIPE', PAYPAL: 'PAYPAL', MOCK: 'MOCK', CASH: 'CASH' });
export const PAYMENT_METHOD = Object.freeze({ CARD: 'CARD', WALLET: 'WALLET', CASH: 'CASH' });
export const REFUND_STATUS = Object.freeze({ REQUESTED: 'REQUESTED', APPROVED: 'APPROVED', REJECTED: 'REJECTED', PROCESSING: 'PROCESSING', REFUNDED: 'REFUNDED', FAILED: 'FAILED' });
export const NOTIFICATION_STATUS = Object.freeze({ PENDING: 'PENDING', SENT: 'SENT', FAILED: 'FAILED', READ: 'READ' });
