import { Router } from 'express';
import validate from '../../middlewares/validate.middleware.js';
import { protect } from '../../middlewares/auth.middleware.js';
import { authorize } from '../../middlewares/role.middleware.js';
import { FINANCE_ROLES } from '../../utils/constants.js';
import * as controller from './report.controller.js';
import { reportQuerySchema } from './report.validator.js';
const router = Router();
router.use(protect, authorize(...FINANCE_ROLES));
router.get('/dashboard', validate(reportQuerySchema), controller.dashboard);
router.get('/sales', validate(reportQuerySchema), controller.sales);
router.get('/events', validate(reportQuerySchema), controller.events);
router.get('/occupancy', validate(reportQuerySchema), controller.occupancy);
router.get('/users', validate(reportQuerySchema), controller.users);
router.get('/export', validate(reportQuerySchema), controller.exportReport);
export default router;
